### ISSUE TITLE
hub doesn't install / not present in path?

### ISSUE THREAD

**Issue by arjunbazinga** [felicianotech/hub-snap#4]
`sudo snap install --classic hub` on my machine running Ubuntu 17.10, completes without any errors.
but hub isn't present in the PATH, and so I have no way of running it. Is this intended behavior?

**Comment by FelicianoTech** [comment]
Hi,

Ubuntu 17.10 is supported by my snap and the reason is that Ubuntu 17.10 isn't a supported distribution anymore by Canonical (the company behind Ubuntu).

The README of this repo will show you the supported distros. Of Ubuntu, it's currently Ubuntu 16.04, Ubuntu 18.04, and Ubuntu 18.10.

If you upgrade to one of those versions and this is still an issue, please let me know.
