### ISSUE TITLE
Any plans to upgrade to non-classic?

### ISSUE THREAD

**Issue by jph00** [felicianotech/hub-snap#8]
Just wondering if you've considered removing the need for "--classic" in this snap? Thanks! :)

**Comment by FelicianoTech** [comment]
Hey @jph00,

This was considered when I made the snap. I had to get special approval from the Snapcraft Team in order to make this a classic snap.

The `hub` snap cannot be a strictly confined snap. At least not anytime soon. It requires access to your system's `git` in order to work, which can't happen in a strictly confined snap.

As Snap and Snapcraft continues to mature and grow, hopefully there will be a way in the future to have a `hub` snap interact with a `git` snap and both be strictly confined. Until then, the `hub` snap will have to  use `--classic`.

**Comment by jph00** [comment]
Many thanks for the explanation!

**Comment by FelicianoTech** [comment]
You're welcome. Thank you for asking.
